### ISSUE TITLE
Disable retext-equality?

### ISSUE THREAD

**Issue by tmcw** [mapbox/retext-mapbox-standard#4]
equality gives a lot of false positives and hasn't turned up any actual corrections in any content.

**Comment by wooorm** [comment]
No actual corrections: is that because Mapbox writes very good docs (I think that’s the case, right?), or because equality/alex is missing stuff?

Too many false positives: :frowning: I’m implementing per-paragraph ignores and a list of ignores for retext-equality soon, which should make this better customisable / easier.

**Comment by tmcw** [comment]
Cool, yeah - so the test set for this is mostly technical documentation and we've had house standards to avoid mistakes like unnecessary gendering for  a long time, so there isn't a ton of opportunity for other types of mistakes.

The false-positives so far:

* `slopes`, in the context of ski maps, is flagged
* `host`, in the context of hostnames
* `disabled`, in the context of an HTML input element (this one's the closest to being valid, because the meaning would be mostly maintained if we switched to a `turned off`, but still have a confusing mismatch with the HTML attribute

**Comment by tmcw** [comment]
After adding message control and updating retext-equality and adding a few ignores, we're down to a pretty low level of false positives!

**Comment by wooorm** [comment]
Cool! :+1:

**Comment by tmcw** [comment]
Closing; with the new wordlist & per-file exclusions, we're good to go.
